### ISSUE TITLE
Values are always in lower case

### ISSUE THREAD

**Issue by Kannas24** [ylax/ConsoleCommon#1]
Values should be case insensitive . I'm always getting argument values in lower case.

**Comment by ylax** [comment]
Hi,

This has been fixed. Was a stupid bug, really... I was doing something like arg.ToLower() for no real reason. Anyways, I don't have time right now to update the Nuget pkg, but the GitHub code is updated.

Thanks - ylax

**Comment by Kannas24** [comment]
Thanks,

I've already modified my version of the code.

**Comment by ylax** [comment]
Awesome, glad you were able to fix it. I have pushed the new version to Nuget as well. Thanks - yl
